name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"  # Triggers the workflow on any tag push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Update version in manifest.json
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          jq --arg v "$tag" '.version = $v' manifest.json > tmp.$$.json && mv tmp.$$.json manifest.json

      - name: Commit updated manifest.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Update manifest.json version to $tag"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css
